### GET EMPLOYESS
GET http://localhost:3000/api/employees
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjMtMDMtMDVUMjI6MDA6MTkuMDAwWiIsInVpZCI6InVLYkpzWUs5dTJoR1c4cXJXUHVDQVFNTUpPbTEiLCJpYXQiOjE2NzgwMzYzMTgsImV4cCI6MTY3ODAzOTkxOH0.8aRJaLEtVjwxpWFU4bv_gR7sFB4QYz2AfW-vU5_MXLM

###
GET http://localhost:3000/api/students

###
GET  http://localhost:3000/api/users
content-type: application/json

{
    "school_id": 1,
    "first_name": "Felix Adrian",
    "last_name": "Masa Pico",
    "email": "adrianmasapico@gmail.com",
    "password": "password123",
    "phone": "+573013171902",
    "address": "Cl 70 Itagui",
    "role": "admin"
  }

###
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "email": "adrianmasapico@gmail.com",
    "password": "password123"
}

###
GET  http://localhost:3000/api/users/check
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjMtMDMtMDVUMjI6MDA6MTkuMDAwWiIsInVpZCI6InVLYkpzWUs5dTJoR1c4cXJXUHVDQVFNTUpPbTEiLCJpYXQiOjE2NzgwMzYzMTgsImV4cCI6MTY3ODAzOTkxOH0.8aRJaLEtVjwxpWFU4bv_gR7sFB4QYz2AfW-vU5_MXLM

###
POST   http://localhost:3000/api/students
content-type: application/json

{
    "school_id": 1,
    "first_name": "Etham",
    "last_name": "Masa",
    "email": "ethammasa@example.com",
    "phone": "555-8866",
    "address": "759 Oak St.",
    "date_of_birth": "2000-12-17",
    "gender": "male"
}

###
PATCH  http://localhost:3000/api/students/4
content-type: application/json

{
    "school_id": 1,
    "first_name": "Etham",
    "last_name": "Masa",
    "email": "ethammasa@example.com",
    "phone": "555-8866",
    "address": "759 Oak St.",
    "date_of_birth": "2000-12-17",
    "gender": "male"
}
###

POST http://localhost:3000/api/schools
content-type: application/json

{
    "name" : "Institucion Educativa Lacides C. Bersal" ,
    "address" : "Cl 12 # 15 - 24 Barrio Nuevo Oriente" ,
    "department" : "Cordoba" ,
    "city" : "Lorica" ,
    "phone" : "666-8709" ,
    "email" : "lacebe@gmail.com" ,
    "shield" : "https://www.ielacides.master2000.net/img/escudo.png" ,
    "dane_code" : "764432667843" ,
    "nit" : "38543547-2" ,
    "resolution" : "Resolcion 645 746 del 54 abril" 
}
###

POST  http://localhost:3000/api/books/matters
content-type: application/json

{
    "matters":[
      { "book_id": 1, "name": "Matematicas", "hours": 3 },
      { "book_id": 1, "name": "Espanol", "hours": 2 },
      { "book_id": 1, "name": "Sociales", "hours": 3 }
    ]
}