### GET EMPLOYESS
GET http://localhost:3000/api/employees
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjMtMDMtMDVUMjI6MDA6MTkuMDAwWiIsInVpZCI6InVLYkpzWUs5dTJoR1c4cXJXUHVDQVFNTUpPbTEiLCJpYXQiOjE2NzgwMzYzMTgsImV4cCI6MTY3ODAzOTkxOH0.8aRJaLEtVjwxpWFU4bv_gR7sFB4QYz2AfW-vU5_MXLM

###
GET http://localhost:3000/api/books

###
GET  http://localhost:3000/api/users
content-type: application/json

{
    "school_id": 1,
    "first_name": "Felix Adrian",
    "last_name": "Masa Pico",
    "email": "adrianmasapico@gmail.com",
    "password": "password123",
    "phone": "+573013171902",
    "address": "Cl 70 Itagui",
    "role": "admin"
  }

###
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "email": "adrianmasapico@gmail.com",
    "password": "password123"
}

###
GET  http://localhost:3000/api/users/check
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwidWlkIjoiZTdsYkM5UmxtellwNXVHWlREWDBFQlE1UmxtMSIsImNyZWF0ZWRfYXQiOiIyMDI0LTAzLTI1VDIxOjE1OjE4LjAwMFoiLCJpYXQiOjE3MTE0Mjc3OTIsImV4cCI6MTcxMTQzMTM5Mn0.sGOyEunUfIlsPwLp9oDmuyJZoF6VjvjHtBHb2aW_ntU

###
GET    http://localhost:3000/api/students
content-type: application/json

{
    "school_id": 1,
    "first_name": "Gylmar Elias",
    "last_name": "Castro Masa",
    "email": "ethammasa@example.com",
    "phone": "444-8866",
    "address": "759 Oak St.",
    "date_of_birth": "2000-12-17",
    "gender": "male"
}

###
PATCH  http://localhost:3000/api/students/4
content-type: application/json

{
    "school_id": 1,
    "first_name": "Etham",
    "last_name": "Masa",
    "email": "ethammasa@example.com",
    "phone": "555-8866",
    "address": "759 Oak St.",
    "date_of_birth": "2000-12-17",
    "gender": "male"
}
###

GET http://localhost:3000/api/schools
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwidWlkIjoiZTdsYkM5UmxtellwNXVHWlREWDBFQlE1UmxtMSIsImNyZWF0ZWRfYXQiOiIyMDI0LTAzLTI1VDIxOjE1OjE4LjAwMFoiLCJpYXQiOjE3MTEzODUwMDUsImV4cCI6MTcxMTM4ODYwNX0.m2Wb0Hh_I0Od1HQa676wJL_QZIJ1ypEYJn3vCA6NzLI

{
    "name" : "Institucion Educativa Lacides C. Bersal" ,
    "address" : "Cl 12 # 15 - 24 Barrio Nuevo Oriente" ,
    "department" : "Cordoba" ,
    "city" : "Lorica" ,
    "phone" : "666-8709" ,
    "email" : "lacebe@gmail.com" ,
    "shield" : "https://www.ielacides.master2000.net/img/escudo.png" ,
    "dane_code" : "764432667843" ,
    "nit" : "38543547-2" ,
    "resolution" : "Resolcion 645 746 del 54 abril" 
}
###

GET   http://localhost:3000/api/books/1/matters
content-type: application/json

{
    "matters":[
      { "book_id": 2, "name": "Matematicas", "hours": 3 },
      { "book_id": 2, "name": "Espanol", "hours": 2 },
      { "book_id": 2, "name": "Sociales", "hours": 3 },
      { "book_id": 2, "name": "Ciencias", "hours": 2 },
      { "book_id": 2, "name": "Ingles", "hours": 2 }
    ]
}

###
GET http://localhost:3000/api/books
content-type: application/json

{
    "school_id": 1,
    "name": "SEXTO B",
    "year": 2000,
    "type": "quantitative"
}

###
POST   http://localhost:3000/api/certificate/student/pdf
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwidWlkIjoiZTdsYkM5UmxtellwNXVHWlREWDBFQlE1UmxtMSIsImNyZWF0ZWRfYXQiOiIyMDI0LTAzLTI1VDIxOjE1OjE4LjAwMFoiLCJpYXQiOjE3MTE3NDMyMzksImV4cCI6MTcxMTc0NjgzOX0.du2zk95qQNznxkeyxyT4tbJZJxsyECz2zOkVk41kjGw

{
    "book_id": 1,
    "student_id": 2
}


###

{"status":200,"data":{"id":2,"school_id":1,"first_name":"Felix Adrian","last_name":"Masa Pico","email":"adrianmasapico@gmail.com","phone":"+573013171902","address":"Cl 70 Itagui","role":"admin","uid":"e7lbC9RlmzYp5uGZTDX0EBQ5Rlm1","created_at":"2024-03-25T21:15:18.000Z","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwidWlkIjoiZTdsYkM5UmxtellwNXVHWlREWDBFQlE1UmxtMSIsImNyZWF0ZWRfYXQiOiIyMDI0LTAzLTI1VDIxOjE1OjE4LjAwMFoiLCJpYXQiOjE3MTE3NDMyMzksImV4cCI6MTcxMTc0NjgzOX0.du2zk95qQNznxkeyxyT4tbJZJxsyECz2zOkVk41kjGw"}}