### GET EMPLOYESS
GET http://localhost:3000/api/employees
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjMtMDMtMDJUMDI6Mzg6MDUuMDAwWiIsInVpZCI6InB1d1VicGR2eHVVaER1YWp0TzdjQ1VoSlpWSDIiLCJpYXQiOjE2Nzc5NTI2NjYsImV4cCI6MTY3Nzk1NjI2Nn0.XmVEAZScPsuCr-j8CfHx95UjXubEfPdBJGVs-Lb4XTw

###
GET http://localhost:3000/api/students

###
POST http://localhost:3000/api/users
content-type: application/json

{
    "school_id": 1,
    "first_name": "Felix Adrian",
    "last_name": "Masa Pico",
    "email": "adrianmasapico@gmail.com",
    "password": "password123",
    "phone": "+573013171902",
    "address": "Cl 70 Itagui",
    "role": "admin"
  }

###
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "email": "adrianmasapico@gmail.com",
    "password": "password123"
}

###
GET  http://localhost:3000/api/users/check
x-access-token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwic2Nob29sX2lkIjoxLCJmaXJzdF9uYW1lIjoiRmVsaXggQWRyaWFuIiwibGFzdF9uYW1lIjoiTWFzYSBQaWNvIiwiZW1haWwiOiJhZHJpYW5tYXNhcGljb0BnbWFpbC5jb20iLCJwaG9uZSI6Iis1NzMwMTMxNzE5MDIiLCJhZGRyZXNzIjoiQ2wgNzAgSXRhZ3VpIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMjMtMDMtMDJUMDI6Mzg6MDUuMDAwWiIsInVpZCI6InB1d1VicGR2eHVVaER1YWp0TzdjQ1VoSlpWSDIiLCJpYXQiOjE2Nzc5NTAzMzcsImV4cCI6MTY3Nzk1MzkzN30.2cVwEVFvo9qTxfvfO0Yc9BLGB9ehCmI49byhlhbNisI"

###
POST   http://localhost:3000/api/students
content-type: application/json

{
    "school_id": 1,
    "first_name": "Etham",
    "last_name": "Masa",
    "email": "ethammasa@example.com",
    "phone": "555-8866",
    "address": "759 Oak St.",
    "date_of_birth": "2000-12-17",
    "gender": "male"
}

###
PATCH  http://localhost:3000/api/students/4
content-type: application/json

{
    "school_id": 1,
    "first_name": "Etham",
    "last_name": "Masa",
    "email": "ethammasa@example.com",
    "phone": "555-8866",
    "address": "759 Oak St.",
    "date_of_birth": "2000-12-17",
    "gender": "male"
}